### ISSUE TITLE
Add currency EUR and others.

### ISSUE THREAD

**Issue by mariushosting** [l4rm4nd/VoucherVault#1]
Nice project! 

Feedback:

I see only the dollars currency. It would be better to add different Currency like EUR and others.

**Comment by l4rm4nd** [comment]
Hey @mariushosting,

thanks for reaching out.

VoucherVault currently does not define any currency at all. What you are seeing is a badly chosen bootstrap icon with the dollar sign. I've replaced the icon with a generic one.

See https://github.com/l4rm4nd/VoucherVault/commit/47175ae7cf54bac1059acabb8f551c15b80b3b7c

Cheers
