### ISSUE TITLE
[FEATURE] Not all coupons have a monetary value, some are a percentage

### ISSUE THREAD

**Issue by chevdor** [l4rm4nd/VoucherVault#13]
**Is your feature request related to a problem? Please describe.**
Providing a monetary value is mandatory but not all coupons have a monetary value. Many are a % discount for the real value is not known.
 
**Describe the solution you'd like**
it should be possible to select `O Value | O Percent`

**Describe alternatives you've considered**
I am currently providing the value 0, not great

**Additional context**
n/a

**Comment by l4rm4nd** [comment]
Hey @chevdor ,

thanks for reaching out.

This is currently implemented in the dev branch. 

Will be included in the next major release.

**Comment by l4rm4nd** [comment]
You can toggle between a monetary and percentage value for coupons now:

![image](https://github.com/user-attachments/assets/f9d2c551-4d33-43cd-8610-71ced4a7c1e1)

**Comment by chevdor** [comment]
That and the other fixes/improvements -> ❤️
