### ISSUE TITLE
[BUG] Dark theme minor issue

### ISSUE THREAD

**Issue by chevdor** [l4rm4nd/VoucherVault#17]
**Describe the bug**
Overall, the dark theme works well. Thanks for implementing it (ref #2).
I spotted however a small issue in the Item distribution chart.

Clicking around while switching the theme leaves the labels of the chart in the wrong color.

## Light theme, too bright

<img width="340" alt="image" src="https://github.com/user-attachments/assets/1aefc709-055c-4a48-b288-47cfcf204a03">

## After some clicking / refresh, Light theme OK
<img width="341" alt="image" src="https://github.com/user-attachments/assets/517bf7b9-4027-4314-830e-8d8ced7ecd10">

## Switching the dark theme, too dark

<img width="336" alt="image" src="https://github.com/user-attachments/assets/4d2b2737-174c-424d-a33e-8a27b5e15894">

## Clicking / refresh: Dark Theme ok
<img width="339" alt="image" src="https://github.com/user-attachments/assets/d399ff9f-d8cc-4c12-8fa1-5d0658d0f970">

 
**Affected version**
1.1.1

**To Reproduce**
1. Sign out
2. Log in
3. Click dashboard
4. See error, and if not...
5. Switch Dark / Light
6. See error

**Expected behavior**
Since the rest works fine, I suspect a small bug when switching themes.

**Screenshots**
See above.

**Additional context**
it is a minor issue since reloading / clicking around eventually solves the issue.

**Comment by l4rm4nd** [comment]
Hi @chevdor 

many thanks!

I've already spotted the issue myself. I personally do not like the light theme anymore and neglected it (🤣) as it can be solved by a simple F5 refresh or using the app onwards once the theme was switched.

It's a very simple fix and applies to the JS frontend only. Once the theme is changed, we have to use JS to toggle the chart legend color.

As there is also a black background flash bug if someone plans to use light theme too, I will fix this sometime in the future.

**Comment by chevdor** [comment]
Yep, totally fair. Honnestly, I would be fine if you close or keep this issue for the day you are bored :)
I don't see a major issue not fixing this and users running into the "issue" can just find this and hit F5 or CMD+R.
