### ISSUE TITLE
[BUG] OIDC callback comes back as http

### ISSUE THREAD

**Issue by Mrs-Feathers** [l4rm4nd/VoucherVault#18]
VoucherVault doesnt respect     "proxy_set_header X-Forwarded-Proto https;" in nginx so when setting up authentik it will cause the endpoint to be given as http and fail.

**Comment by l4rm4nd** [comment]
Hi @Mrs-Feathers ,

many thanks for reaching out.

This is already a known issue discussed here:

https://github.com/mozilla/mozilla-django-oidc/issues/417

In the meantime, you can just add a redirect url on your IdP for both URL protocols (HTTP and HTTPS). Works on my side, as the reverse proxy should issue an automatic upgrade from HTTP to HTTPS and terminates TLS anyways.

**Comment by Mrs-Feathers** [comment]
in the guide you say "Add two redirect urls (http://<FQDN>/oidc/callback/ and http://<FQDN>/oidc/callback/). Replace with your domain name."

did you mean http and https? other wise theyre both the same, i think its a typo

**Comment by Mrs-Feathers** [comment]
i can confirm it works, however im getting a 500 error now

**Comment by l4rm4nd** [comment]
> i can confirm it works, however im getting a 500 error now

Re-check your Authentik OIDC params defined as env variables. Ensure that you have named the Provider and Application  `vouchervault`.

On Authentik, the application name impacts and is included in the JWKS URL. May browse the summary page of your provider in authentik and validate.

Alternatively, enable the DEBUG mode via environment variables and see what errors are thrown in VoucherVault.

**Comment by Mrs-Feathers** [comment]
thank you! i was able to use debug to figure out that i needed to use HS256 with authentik rather than the default in the docker-compose file which was RS256. it works perfect now! thank you for your help!

**Comment by l4rm4nd** [comment]
> thank you! i was able to use debug to figure out that i needed to use HS256 with authentik rather than the default in the docker-compose file which was RS256. it works perfect now! thank you for your help!

Sure, no worries. Glad you got it working.

Funnily, I had to use RS256 instead of HS256. Will have a look at my Authentik config why that's the case.

**Comment by l4rm4nd** [comment]
> The signing key is not strictly required, if no signing key is selected, the OAuth provider uses HS256 to sign the JWTs (which is a symmetric signature method that allows verifying the JWT with the client_secret value), and if a signing key is selected, then RS256/ES256 are used for signing, which allow for verification of the JWT with the public key.

Okay, so it depends what one selects when creating the `Provider` under `Signing Key`.

My Authentik instances uses the self-signed certificate, which will lead to `RS256` instead of your `HS256`, as you left the input field empty.
