### ISSUE TITLE
Vouchervault fails to load with "unable to open database file" error

### ISSUE THREAD

**Issue by rama31244** [l4rm4nd/VoucherVault#19]
Hi
I just attempted to run Vouchervault on docker (using an unraid template) and it failed to load due to an error with opening the database. I've included the log file below. Any idea what might be causing this? TIA

[VoucherVault-2024-07-30T10-39-43.log](https://github.com/user-attachments/files/16426417/VoucherVault-2024-07-30T10-39-43.log)

**Comment by l4rm4nd** [comment]
https://github.com/l4rm4nd/VoucherVault/wiki/01-%E2%80%90-Installation#permissions

**Comment by rama31244** [comment]
Thanks for the prompt reply. I tried running that command in the container but it said there's no such folder. Could it be in a different location due to being an unraid template? Sorry, i'm fairly new to docker

**Comment by l4rm4nd** [comment]
Maybe this helps:

https://www.youtube.com/watch?v=lu9o-y2ZGNM

Ensure to properly map the bind mount paths.

Also do not forget to also spawn a redis container this way.

**Comment by l4rm4nd** [comment]
Or directly use docker compose on Unraid.

There seems also to be a plugin for docker compose:

- https://docs.ibracorp.io/docker-compose/docker-compose-for-unraid

**Comment by rama31244** [comment]
Ok thanks, I'll have a play around with the different mounting options. Thanks again for ur advice

**Comment by rama31244** [comment]
I managed to resolve the permissions issues by changing the ownership of the opt/app/database folder to www-data but the webui still doesn't load, instead saying 'bad request (400)'. No obvious errors in the log, it just hangs on "[i] Spawning the application server" now. Any idea what this might be?

**Comment by l4rm4nd** [comment]
> I managed to resolve the permissions issues by changing the ownership of the opt/app/database folder to www-data but the webui still doesn't load, instead saying 'bad request (400)'. No obvious errors in the log, it just hangs on "[i] Spawning the application server" now. Any idea what this might be?

You have to set the environment variable `DOMAIN` to either the IP address or FQDN.

This must match the URL you are trying to access VoucherVault on.

**Comment by l4rm4nd** [comment]
May read the new wiki entry regarding installation on Unraid:

https://github.com/l4rm4nd/VoucherVault/wiki/01-%E2%80%90-Installation#unraid-installation

**Comment by rama31244** [comment]
Thanks, I realised my problem was that I had the vouchervault port number appended to my unraid IP in the DOMAIN variable. Once I removed this, everything worked perfectly. It's a great application, thanks again for your help

**Comment by rama31244** [comment]
Just one last question, is there a way to make it so that all users have a shared inventory? I've created a group and added multiple users but the content is still seperate

**Comment by l4rm4nd** [comment]
> Just one last question, is there a way to make it so that all users have a shared inventory? I've created a group and added multiple users but the content is still seperate

This is currently not implemented.

Each user has his own account and own items. There is no sharing feature.

You would have to use and share one account, if you plan to share items.

**Comment by rama31244** [comment]
All good, I was using OIDC so it created multiple users but I'll just make it so that we're sharing the one account

**Comment by l4rm4nd** [comment]
> All good, I was using OIDC so it created multiple users but I'll just make it so that we're sharing the one account

Will think about implementing a sharing feature. Maybe as separate dataroom, where all shared items are listed to not be mixed with own, private ones. 

Should be fairly easy to implement. Just have to think about it and find the time.

Definitely added to the feature list.

**Comment by rama31244** [comment]
Love your work. Keep it up!

**Comment by rama31244** [comment]
Until the sharing feature is implemented, I'm trying to set it up so that OIDC through Authentik always logs in as the same user regardless of which Authentik user is logged in. I think this can be achieved through scope mapping. Do you know which scope I need to map to make this work?

**Comment by l4rm4nd** [comment]
Hey @rama31244 ,

we are using the OIDC library provided by Mozilla. The claim, which is validated, is the user account's email address in Django.  You user accounts on Authentik would have to reflect the same e-mail-address, which is not possible I assume (unique required).

> By default, mozilla-django-oidc looks up a Django user matching the email field to the email address returned in the user info data from the OIDC provider.

https://mozilla-django-oidc.readthedocs.io/en/stable/installation.html#connecting-oidc-user-identities-to-django-users

I don't think there is a possibility to change this. I would have to adjust the code specifically to validate other claims, which is not planned.

https://mozilla-django-oidc.readthedocs.io/en/stable/installation.html#advanced-user-verification-based-on-their-claims

**Comment by rama31244** [comment]
That makes sense. I tried using the property mapping to make all my authentik users return the same email address but the OIDC stopped working. I'll just turn off OIDC and get everyone in the house to use the same user account for now until sharing feature is implemented. Thanks

**Comment by l4rm4nd** [comment]
> Until the sharing feature is implemented, I'm trying to set it up so that OIDC through Authentik always logs in as the same user regardless of which Authentik user is logged in. I think this can be achieved through scope mapping. Do you know which scope I need to map to make this work?

v1.6.0 implements sharing.

**Comment by rama31244** [comment]
Amazing, it was super intuitive to use too. Thanks again
I'll be recommending VoucherVault to my friends
