### ISSUE TITLE
Add Dark Theme

### ISSUE THREAD

**Issue by mariushosting** [l4rm4nd/VoucherVault#2]
It would be great to have a Dark Theme too.

**Comment by l4rm4nd** [comment]
Hey @mariushosting,

good idea.

Will have a look how to adjust the Niceadmin bootstrap template accordingly. May take a while.

**Comment by l4rm4nd** [comment]
I've implemented dark mode.

You can choose between light and dark theme via the UI.

https://github.com/l4rm4nd/VoucherVault/commit/40d833f1082b5acb4b215e0c81edd2656108e08d
