### ISSUE TITLE
[FEATURE] Redis Settings

### ISSUE THREAD

**Issue by drag0n141** [l4rm4nd/VoucherVault#22]
Hey,

it would be nice to set the REDIS_PORT and REDIS_DATABASE. In your Code it is default to Port 6379 and default database 0.

And its not possible to add an REDIS Password. I think the easiest way is to let use set the complete REDIS_URL as ENV.

**Comment by l4rm4nd** [comment]
Hey  @drag0n141 ,

the old `REDIS_HOST` environment variable was rather useless anyways.

I've switched to `REDIS_URL` now, which allows you to configure a custom redis url.

As some people may have already defined a custom redis hostname, I introduce it as new feature by bumping the minor version again.

Cheers
