### ISSUE TITLE
[BUG] Database does not generate on Unraid

### ISSUE THREAD

**Issue by Joshndroid** [l4rm4nd/VoucherVault#24]
**Describe the bug**
Hello, it would appear that something is not setup correctly in the unraid template.
I have changed the domain, reverse proxy section and added redis and pressed done, it says it works successfully however it can be seen in the logs it appears it cannot find a db..... your permissions changes likely not going to work as expected in unraid.

**Affected version**
latest

**Additional context**

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 136, in inner_run
    self.check_migrations()
  File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 581, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/migrations/recorder.py", line 89, in applied_migrations
    if self.has_table():
       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/migrations/recorder.py", line 63, in has_table
    with self.connection.cursor() as cursor:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 316, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 292, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 274, in ensure_connection
    with self.wrap_database_errors:
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 275, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 181, in get_new_connection
    conn = Database.connect(**conn_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: unable to open database file
```

**Comment by l4rm4nd** [comment]
Hi @Joshndroid 

many thanks for reaching out.

The Unraid template was not created by me, so no idea whether it is valid or not.

In general, you just have to ensure that the database can be written to disk. So ensure that the bind mount volume is RW by Docker or in your case Unraid.

Adjust the share permissions accordingly. This is likely done in the UI. 

Via the CLI it would be something like this:

````
sudo chmod -R 777 <path-to-volume-dir>
````

**Comment by l4rm4nd** [comment]
Hi @Joshndroid 

many thanks for reaching out.

The Unraid template was not created by me, so no idea whether it is valid or not.

In general, you just have to ensure that the database can be written to disk. So ensure that the bind mount volume is RW by Docker or in your case Unraid.

Adjust the share permissions accordingly. This is likely done in the UI. 

Via the CLI it would be something like this:

````
sudo chmod -R 777 <path-to-volume-dir>
````

**Comment by l4rm4nd** [comment]
Habe you fixed it already @Joshndroid?

If so, please outline what the exact issue was. So others may learn about it too.

Thanks in advance!

**Comment by l4rm4nd** [comment]
May read:

https://github.com/l4rm4nd/VoucherVault/wiki/01-%E2%80%90-Installation#unraid-installation

**Comment by Joshndroid** [comment]
Hey mate.
Apologies I realised you didn't make the template so I closed the issue.
I must live on the other side of the world to you, I am going to have a further play today

**Comment by l4rm4nd** [comment]
> Hey mate.
> Apologies I realised you didn't make the template so I closed the issue.
> I must live on the other side of the world to you, I am going to have a further play today

Hey @Joshndroid ,

all good, I am here to help.

If you have any further issues, feel free to ask. In the meantime, I will try to publish an official Unraid template myself.

**Comment by Joshndroid** [comment]
So i got it up and running.
I noticed that within the domain setting I had to have the domain as the entire address...
domain.com -> did not work
voucher.domain.com -> did work... 
That's probably just me still not under standing FQDN after all these years lol
I am running behind a reverse proxy

**Comment by l4rm4nd** [comment]
> I noticed that within the domain setting I had to have the domain as the entire address...

Yeah, you have to put the FQDN. So the full hostname with subdomain. Basically the URL's hostname you plan on accessing VoucherVault later on. Is unfortunately mandatory due to Django's security measures applied.

> I am running behind a reverse proxy

If you use TLS (HTTPS), also set the `SECURE_COOKIES` environment variable to `True`.

> Yeah I would like an official template if possible.

I will publish an official template to the Unraid Store. The repository is already up, but Squish (Unraid dev) must publish it.

https://github.com/l4rm4nd/unraid-templates

> Creating a template is the somewhat easy part.... helping people when there is a bit of background setup involved is the more important part

True that.

At least I have a wiki with [install instructions for unraid](https://github.com/l4rm4nd/VoucherVault/wiki/01-%E2%80%90-Installation#unraid-installation).

**Comment by Joshndroid** [comment]
> 
> > I am running behind a reverse proxy
> 
> If you use TLS (HTTPS), also set the `SECURE_COOKIES` environment variable to `True`.

Yep, I have this set to true, everything appears to be working as intended at this time. Working on getting a few loyalty cards in at the moment

> 
> > Yeah I would like an official template if possible.
> 
> I will publish an official template to the Unraid Store. The repository is already up, but Squish (Unraid dev) must publish it.
> 
> https://github.com/l4rm4nd/unraid-templates

Excellent, yeah I have generated a few templates over the years it usually takes a few hours up to a day for the template to get merged.

> 
> > Creating a template is the somewhat easy part.... helping people when there is a bit of background setup involved is the more important part
> 
> True that.
> 
> At least I have a wiki with [install instructions for unraid](https://github.com/l4rm4nd/VoucherVault/wiki/01-%E2%80%90-Installation#unraid-installation).

I checked those out while I was having another play this morning.

Thanks again, cool program.
Trying to possibly get off catima, which although is also cool, not exactly share friendly...

**Comment by l4rm4nd** [comment]
An official Unraid app template was published today.

Feel free to use it.

![image](https://github.com/user-attachments/assets/86198b54-388e-4b1c-8b49-e0059ac986a8)
