### ISSUE TITLE
[FEATURE] Checkbox to disable issue/expiry date for loyalty cards

### ISSUE THREAD

**Issue by Joshndroid** [l4rm4nd/VoucherVault#25]
When adding a loyalty card, please enable the ability for the card to be set with no dates applied.
Usually where I reside, a loyalty card remains valid until you lose it or the business changes hands, etc.
I understand that possibly where other's reside that this may be different.
This also will clean up the UI with the date/s removed from the dashboard card

Workaround at the moment is to just have a wildly long expiry date

**Comment by l4rm4nd** [comment]
Good idea.

The initial idea behind VoucherVault was giftcard management. Also with a heavy focus on being reminded.

Due to this, the expiry date is still mandatory for all item types.

Can be easily fixed though. In the meantime, as you said, just define a wildly long expiry date.

**Comment by Joshndroid** [comment]
The other thing for some countries/states is that there is no expiry at all for gift cards as per local legislation (hooray) so its possible the checkbox may be expanded into the gift card area as well :)

**Comment by l4rm4nd** [comment]
> The other thing for some countries/states is that there is no expiry at all for gift cards as per local legislation (hooray) so its possible the checkbox may be expanded into the gift card area as well :)

That's interesting.

I am from Germany and all giftcards will expire at some time. Most often, after 3 years but it is basically up to the store selling those.

Having no expiry per law is quite nice for the end user. Basically no impact when forgetting to redeem something.

**Comment by l4rm4nd** [comment]
The expiry date is now optional in the UI.

If unset, an expiry date 50 years in the future is set. 

This was the easiest option to implement it, without adjusting the code for expiry notifications itself and some other functions.
