### ISSUE TITLE
[FEATURE] Keep values when there is an error on submit

### ISSUE THREAD

**Issue by TheZoker** [l4rm4nd/VoucherVault#29]
**Is your feature request related to a problem? Please describe.**
When there is an error submitting the new item form, all values are cleared. I would prefer if all values would still be available in the fields instead. 

1. Go to `Create New Item`
2. Don't fill the `Issuer` field (which should be required btw)
3. Submit

**Describe the solution you'd like**
Keep all values on submit 

**Describe alternatives you've considered**

**Additional context**

**Comment by l4rm4nd** [comment]
If such an error occurs, you can simply use the the browser's back feature and get the previously filled out forms.

Should not happen anymore, as issuer field is required in v1.5.1.
