### ISSUE TITLE
Feature requests for giftcards

### ISSUE THREAD

**Issue by wardwygaerts** [l4rm4nd/VoucherVault#3]
Nice project! I have some feature request:
* I often don't use my giftcards in one time (sometimes multiple purchase) so I have some remaining money on it, maybe a possibility to add the amount that's already used, so we can see the exact amount that's still available.
* Option to upload a pdf/image of the original voucher/giftcard.
* For giftcards, there's often also a pincode provided to use online. I add this now in the description box, but maybe a dedicated (secure) textbox would ben better.

**Comment by l4rm4nd** [comment]
Hey @wardwygaerts.

I've implemented the PIN code feature. New Docker image is built and available on Dockerhub. Thanks for pointing this out!

For the future, I may implement:

- a transaction history. So you can keep note of your giftcard expenses with a little description and see how much value is left.
- an option to upload a pdf or image. Seems like a cool idea, especially, if someone plans to go full digital and throw the original voucher/giftcard into the bin.

**Comment by l4rm4nd** [comment]
I've also added a transaction history.

**Comment by l4rm4nd** [comment]
File upload may be planned for the future.

Closing this issue ticket for now.

Thanks!

**Comment by l4rm4nd** [comment]
FYI: File upload was introduced
