### ISSUE TITLE
[FEATURE] Allow to translate application

### ISSUE THREAD

**Issue by TheZoker** [l4rm4nd/VoucherVault#32]
**Is your feature request related to a problem? Please describe.**
Would be nice, if I could use the app in my own language. I would also provide translations for German :)

**Describe the solution you'd like**
Add translation to the app

**Describe alternatives you've considered**

**Additional context**

**Comment by l4rm4nd** [comment]
I am native German myself. So translation would be no problem.

However, I would have to research about adding automatic translations into Django. I know there is native support but the implementation is still unknown to me.

Translations are not planned atm. Depending on the complexity, I will consider implementing it.

Thanks!

**Comment by l4rm4nd** [comment]
You can toggle between English and German in the sidebar.

![image](https://github.com/user-attachments/assets/827133ba-f55a-433b-9cd6-f5cf104387bf)
