### ISSUE TITLE
[FEATURE] Light/Dark Mode based on system settings

### ISSUE THREAD

**Issue by steffenrapp** [l4rm4nd/VoucherVault#35]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Many apps and Web apps have an option to use the Light/Dark Mode based on system settings. In VoucherVault you can only manually switch between the two modes. It world be great to have an option for automatic switching based on the OS's setting.

**Describe alternatives you've considered**

**Additional context**

**Comment by l4rm4nd** [comment]
The default theme is dark mode. You can easily switch to light mode via the frontend.

The choice is stored on the clientside in localstorage for the future.

No plans on using the system default as theme.
