### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by mariushosting** [l4rm4nd/VoucherVault#4]
It would be better to have a changelog to be able too see the VoucherVault changelog.

**Comment by l4rm4nd** [comment]
Hey @mariushosting ,

sorry for the inconvenience and the many code changes yesterday.

Major code changes should be done now. Ready for the first stable release.

I'll have a look into fine-tuning the GitHub action. It should be possible to automatically create individual Docker image tags with a release note and changelog. Also focusing on an ARM build.

**Comment by l4rm4nd** [comment]
Implemented conventional commits with a new CI workflow.
