### ISSUE TITLE
[FEATURE] Support for running on subfolders

### ISSUE THREAD

**Issue by MagiX13** [l4rm4nd/VoucherVault#40]
**Is your feature request related to a problem? Please describe.**
I run all my services on the same domain, within different folders, as such: https://example.com/VoucherVault

**Describe the solution you'd like**
Defining an environment variable (e.g. `SUBFOLDER=VoucherVault`) in the docker compose should make the website available at https://example.com/VoucherVault (e.g. [via the SCRIPT_NAME](https://docs.djangoproject.com/en/5.1/ref/settings/#force-script-name)

**Describe alternatives you've considered**
I think hosting a variety of services in different subdomains comes with some risk, e.g. exposing which services are running and can potentially open yourself to a wide variety of issues.

**Comment by l4rm4nd** [comment]
Hi @MagiX13 ,

many thanks for your suggestion.

Though, as with many other software projects, I typically won't implement support for subpath routing.

The reasons for this:

- Subpath routing is basically security through obscurity. Although one may argue that it's defense in depth, which may is, it's still easily possible to enumerate directories and filenames. Same holds true for subdomains. Only targeted attacks will enumerate your domains and subpaths typically. The automated bot scans are braindead.
- Subpath routing is often not supported by many frameworks and requires manual routing adjustments.
- Subpath routing may affect cookie scoping and therefore reduce security. May rethink whether running everything on the same domain is really more secure.

I've seen a quick fix or implementation for Django regarding subpath routing  [here](https://stackoverflow.com/a/28407366). So you may bind mount the `settings.py` and add your subpath. Not tested though.

Will tinker a bit. If it's easy to implement I may do the favor.

**Comment by l4rm4nd** [comment]
The implementation for Django is not straight-forward. Will not implement.

**Comment by MagiX13** [comment]
Many thanks for the feedback. 

I looked into this a bit as well and it seems to be unsupported by the `i18n_patterns` as well, so even adding the `FORCE_SCRIPT_NAME` is not sufficient. I thus agree that this is not trivial to implement.

On the security through obscurity point: I in general agree with that, but there is quite a bit of information "hidden" in the certificate chains (e.g. crt.sh) that might give some information on what services are run - without the need for enumeration, making such attacks much more realistic.

Would you be open to a PR in case I can find a reasonable implementation approach?
