### ISSUE TITLE
Crontab default task

### ISSUE THREAD

**Issue by lksrmp** [l4rm4nd/VoucherVault#8]
Default scheduling for notifications `*/14400 * * * *` causes execution every hour. I would suggest something like `0 6 * * 1` for every Monday at 6am.

**Comment by l4rm4nd** [comment]
Have you confirmed that the default configured crontab runs every minute? It should only run every 10 days. Does so in my environment. Will test now again.

Anyways, you are free to define your own schedule/interval/crontab via the admin panel.

I would only adjust if it is a bug.

**Comment by lksrmp** [comment]
I connected it to Telegram and got notifications every full hour. Already adjusted mine, thanks.
[crontab guru](https://crontab.guru/#*/14400_*_*_*_*) describes the setting as “At every 14400th minute” but clicking on "next" underneath reveals
```
next at 2024-07-18 17:00:00
then at 2024-07-18 18:00:00
then at 2024-07-18 19:00:00
then at 2024-07-18 20:00:00
then at 2024-07-18 21:00:00
```

**Comment by l4rm4nd** [comment]
> I connected it to Telegram and got notifications every full hour.

Hmm that's weird. I've tested my instance also but do not receive hourly expiry notifications.

I'll update the default to run once a week. I don't like the `*/14400` anyways and it's based on the time VoucherVoult was spawned, which is also not that beneficial.

**Comment by l4rm4nd** [comment]
See https://github.com/l4rm4nd/VoucherVault/commit/2741ef84b4735ebcaaf9e7e6c3d1705f39aba8b0
