### ISSUE TITLE
Feature request: Optional fields

### ISSUE THREAD

**Issue by lksrmp** [l4rm4nd/VoucherVault#9]
Great project! So helpful to keep track of gift cards laying around.

Is it possible to somehow leave fields optional? Many analog gift cards (restaurants etc.) do not come with any redeem or pin codes. Some also do not expire or at least it is not stated. It would be great if fields could just be left empty instead of making up false data for them.
Of course you then can not directly redeem them from VoucherVault but it is very convenient to use it as on inventory list for such gift cards.

**Comment by l4rm4nd** [comment]
Hey @lksrmp ,

the pin code field is already optional. If you do not supply it, it will not be displayed in the frontend later.

The redeem code is currently mandatory. 

So if I understand correctly, you have giftcards that do not have any kind of code, number, ID or whatsoever to legimitate a redemption? Do you have to bring the giftcard in physical form then when redeeming it?

**Comment by lksrmp** [comment]
Yes, you need to bring the physical giftcard which has a stamp and signature from for example the restaurant (especially smaller once without IT systems). I still would put those into VoucherVault as it helps me to keep track of what I have still laying around. 
However, I can also just enter placeholder data. Just thought it might help some people if it is a quick fix. I don't think it is necessary if it would require significant ressources.

**Comment by l4rm4nd** [comment]
> Yes, you need to bring the physical giftcard which has a stamp and signature from for example the restaurant (especially smaller once without IT systems). I still would put those into VoucherVault as it helps me to keep track of what I have still laying around. However, I can also just enter placeholder data. Just thought it might help some people if it is a quick fix. I don't think it is necessary if it would require significant ressources.

There are plans for implementing a file upload feature, where users can upload a screenshot or PDF of the giftcard/voucher/coupon. Once this is implemented, I may remove `required` on the redeem code field.

In the meantime, please just insert a bogus value.
